spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_management_system
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET:ThisIsMySuperSecretKeyForJwtSigning12345}
    expiration-ms: 3600000